/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.lexer;

import java.io.*;
import lexing.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNum(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKeywords(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFloatNum(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCharConst(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStrConst(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdent(text, line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAssign(line, pos); }
    Token new7(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TArithOp(text, line, pos); }
    Token new8(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRelOp(text, line, pos); }
    Token new9(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLogOp(text, line, pos); }
    Token new10(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSpecChar(text, line, pos); }
    Token new11(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParen(text, line, pos); }
    Token new12(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new13(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUnknown(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{0, 9, 1}, {10, 10, 2}, {11, 31, 1}, {32, 32, 3}, {33, 33, 4}, {34, 34, 5}, {35, 36, 1}, {37, 37, 6}, {38, 38, 7}, {39, 39, 1}, {40, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {46, 46, 13}, {47, 47, 14}, {48, 57, 15}, {58, 58, 1}, {59, 59, 16}, {60, 60, 17}, {61, 61, 18}, {62, 62, 19}, {63, 63, 20}, {64, 64, 1}, {65, 90, 21}, {91, 91, 1}, {92, 92, 22}, {93, 96, 1}, {97, 97, 23}, {98, 98, 24}, {99, 99, 25}, {100, 100, 26}, {101, 101, 27}, {102, 102, 28}, {103, 104, 23}, {105, 105, 29}, {106, 111, 23}, {112, 112, 30}, {113, 114, 23}, {115, 115, 31}, {116, 118, 23}, {119, 119, 32}, {120, 122, 23}, {123, 123, 33}, {124, 124, 34}, {125, 125, 35}, {126, 65535, 1}, },
            {},
            {{10, 10, 36}, {32, 32, 37}, {92, 92, 38}, },
            {{10, 92, -4}, },
            {{61, 61, 39}, },
            {{32, 32, 40}, {34, 34, 41}, {37, 37, 42}, {46, 46, 43}, {48, 57, 44}, {65, 90, 45}, {97, 122, 46}, },
            {},
            {{38, 38, 47}, },
            {},
            {},
            {{43, 43, 48}, },
            {},
            {{45, 45, 49}, },
            {},
            {},
            {{46, 46, 50}, {48, 57, 51}, },
            {},
            {{61, 61, 52}, },
            {{61, 61, 53}, },
            {{61, 61, 54}, },
            {},
            {{48, 57, 55}, {65, 90, 56}, {95, 95, 57}, {97, 122, 58}, },
            {{110, 110, 59}, {116, 116, 60}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 110, 58}, {111, 111, 61}, {112, 113, 58}, {114, 114, 62}, {115, 122, 58}, },
            {{48, 95, -23}, {97, 97, 63}, {98, 103, 58}, {104, 104, 64}, {105, 110, 58}, {111, 111, 65}, {112, 122, 58}, },
            {{48, 95, -23}, {97, 100, 58}, {101, 101, 66}, {102, 110, 58}, {111, 111, 67}, {112, 122, 58}, },
            {{48, 95, -23}, {97, 107, 58}, {108, 108, 68}, {109, 122, 58}, },
            {{48, 107, -29}, {108, 108, 69}, {109, 110, 58}, {111, 111, 70}, {112, 122, 58}, },
            {{48, 95, -23}, {97, 101, 58}, {102, 102, 71}, {103, 109, 58}, {110, 110, 72}, {111, 122, 58}, },
            {{48, 95, -23}, {97, 113, 58}, {114, 114, 73}, {115, 122, 58}, },
            {{48, 95, -23}, {97, 118, 58}, {119, 119, 74}, {120, 122, 58}, },
            {{48, 95, -23}, {97, 103, 58}, {104, 104, 75}, {105, 122, 58}, },
            {},
            {{124, 124, 76}, },
            {},
            {{10, 92, -4}, },
            {{10, 92, -4}, },
            {{110, 116, -24}, },
            {},
            {{32, 34, -7}, {46, 57, -7}, {65, 90, 77}, {97, 122, 78}, },
            {},
            {{99, 99, 79}, {100, 100, 80}, {102, 102, 81}, {108, 108, 82}, },
            {{32, 122, -42}, },
            {{32, 122, -42}, },
            {{32, 32, 40}, {34, 34, 83}, {46, 122, -42}, },
            {{32, 122, -47}, },
            {},
            {},
            {},
            {{48, 57, 84}, },
            {{46, 57, -17}, },
            {},
            {},
            {},
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{10, 92, -4}, },
            {{10, 92, -4}, },
            {{48, 110, -26}, {111, 111, 85}, {112, 122, 58}, },
            {{48, 100, -28}, {101, 101, 86}, {102, 122, 58}, },
            {{48, 95, -23}, {97, 114, 58}, {115, 115, 87}, {116, 122, 58}, },
            {{48, 95, -23}, {97, 97, 88}, {98, 122, 58}, },
            {{48, 95, -23}, {97, 109, 58}, {110, 110, 89}, {111, 122, 58}, },
            {{48, 101, -31}, {102, 102, 90}, {103, 122, 58}, },
            {{48, 95, -23}, {97, 116, 58}, {117, 117, 91}, {118, 122, 58}, },
            {{48, 114, -65}, {115, 115, 92}, {116, 122, 58}, },
            {{48, 110, -26}, {111, 111, 93}, {112, 122, 58}, },
            {{48, 113, -32}, {114, 114, 94}, {115, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 115, 58}, {116, 116, 95}, {117, 122, 58}, },
            {{48, 95, -23}, {97, 104, 58}, {105, 105, 96}, {106, 122, 58}, },
            {{48, 104, -75}, {105, 105, 97}, {106, 122, 58}, },
            {{48, 104, -75}, {105, 105, 98}, {106, 122, 58}, },
            {},
            {{32, 122, -42}, },
            {{32, 122, -42}, },
            {{92, 92, 99}, },
            {{92, 92, 100}, },
            {{92, 92, 101}, },
            {{102, 102, 102}, },
            {},
            {{48, 57, 84}, },
            {{48, 107, -29}, {108, 108, 103}, {109, 122, 58}, },
            {{48, 95, -23}, {97, 97, 104}, {98, 122, 58}, },
            {{48, 100, -28}, {101, 101, 105}, {102, 122, 58}, },
            {{48, 113, -32}, {114, 114, 106}, {115, 122, 58}, },
            {{48, 114, -65}, {115, 115, 107}, {116, 116, 108}, {117, 122, 58}, },
            {{48, 95, -23}, {97, 97, 109}, {98, 122, 58}, },
            {{48, 95, -23}, {97, 97, 58}, {98, 98, 110}, {99, 122, 58}, },
            {{48, 100, -28}, {101, 101, 111}, {102, 122, 58}, },
            {{48, 95, -23}, {97, 97, 112}, {98, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 109, -67}, {110, 110, 113}, {111, 122, 58}, },
            {{48, 115, -74}, {116, 116, 114}, {117, 122, 58}, },
            {{48, 107, -29}, {108, 108, 115}, {109, 122, 58}, },
            {{110, 110, 116}, },
            {{110, 110, 117}, },
            {{110, 110, 118}, },
            {{92, 92, 119}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 106, 58}, {107, 107, 120}, {108, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 115, -74}, {116, 116, 121}, {117, 122, 58}, },
            {{48, 104, -75}, {105, 105, 122}, {106, 122, 58}, },
            {{48, 116, -69}, {117, 117, 123}, {118, 122, 58}, },
            {{48, 107, -29}, {108, 108, 124}, {109, 122, 58}, },
            {{32, 32, 125}, {48, 122, -23}, },
            {{48, 115, -74}, {116, 116, 126}, {117, 122, 58}, },
            {{48, 115, -74}, {116, 116, 127}, {117, 122, 58}, },
            {{48, 95, -23}, {97, 98, 58}, {99, 99, 128}, {100, 122, 58}, },
            {{48, 100, -28}, {101, 101, 129}, {102, 122, 58}, },
            {{34, 34, 130}, },
            {{34, 34, 131}, },
            {{34, 34, 132}, },
            {{110, 110, 133}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 109, -67}, {110, 110, 134}, {111, 122, 58}, },
            {{48, 107, -29}, {108, 108, 135}, {109, 122, 58}, },
            {{48, 100, -28}, {101, 101, 136}, {102, 122, 58}, },
            {{105, 105, 137}, },
            {{48, 122, -23}, },
            {{48, 101, -31}, {102, 102, 138}, {103, 122, 58}, },
            {{48, 103, -34}, {104, 104, 139}, {105, 122, 58}, },
            {{48, 122, -23}, },
            {},
            {},
            {},
            {{34, 34, 140}, },
            {{48, 116, -69}, {117, 117, 141}, {118, 122, 58}, },
            {{48, 115, -74}, {116, 116, 142}, {117, 122, 58}, },
            {{48, 122, -23}, },
            {{102, 102, 143}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {},
            {{48, 100, -28}, {101, 101, 144}, {102, 122, 58}, },
            {{48, 122, -23}, },
            {},
            {{48, 122, -23}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 13, 12, 12, 9, 13, 7, 13, 11, 7, 7, 10, 7, 10, 7, 0, 10, 8, 6, 8, 10, 5, 13, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 10, 13, 10, 12, 12, -1, 8, -1, 4, -1, -1, -1, -1, -1, 9, 7, 7, -1, 0, 8, 8, 8, 5, 5, 5, 5, 12, 12, 5, 5, 5, 5, 5, 5, 1, 5, 5, 5, 1, 5, 5, 5, 5, 9, -1, -1, -1, -1, -1, -1, 3, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 5, 5, 5, -1, -1, -1, -1, 1, 5, 1, 1, 5, 5, 5, 5, 1, 5, 5, 5, 5, -1, -1, -1, -1, 1, 1, 5, 5, 5, -1, 1, 5, 5, 1, 1, 1, 1, -1, 5, 5, 1, -1, 1, 1, 1, 5, 1, 1, 1, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
