/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.analysis;

import lexing.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTNum(TNum node);
    void caseTKeywords(TKeywords node);
    void caseTFloatNum(TFloatNum node);
    void caseTCharConst(TCharConst node);
    void caseTStrConst(TStrConst node);
    void caseTIdent(TIdent node);
    void caseTAssign(TAssign node);
    void caseTArithOp(TArithOp node);
    void caseTRelOp(TRelOp node);
    void caseTLogOp(TLogOp node);
    void caseTSpecChar(TSpecChar node);
    void caseTParen(TParen node);
    void caseTBlank(TBlank node);
    void caseTUnknown(TUnknown node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
